### ISSUE TITLE
AttributeError: module 'openreview' has no attribute 'Client'

### ISSUE THREAD

**Issue by rrryan2016** [hlhllh/download-conference-pdf#1]

**Comment by rrryan2016** [comment]
Occured when running `pdf_down_openreview.py`

**Comment by hlhllh** [comment]
Hi,
Plz make sure that you install `openreview` package by `pip install openreview-py` rather than `pip install openreview`.

**Comment by rrryan2016** [comment]
Thanks, sorry for my carelessness.
