### ISSUE TITLE
Can pdf_down_openreview.py easily be switched to download accepted paper?

### ISSUE THREAD

**Issue by rrryan2016** [hlhllh/download-conference-pdf#2]
I noticed that you download all submitted papers concerning to RL in `pdf_down_openreview.py`?

Is it available to swicth this code easily to download accepted paper in ICLR 2021. 

Thanks in advance. 😄

**Comment by hlhllh** [comment]
Yes. Although I do not try, you could refer to [https://openreview-py.readthedocs.io/en/latest/getting_data.html#retrieving-all-accepted-submissions-for-a-conference-double-blind](url) to change line 27 in the file.

**Comment by rrryan2016** [comment]
Released code to download all accepted ICLR 2021 paper: https://github.com/rrryan2016/CV_conference_paper_download/tree/main/ICLR2021.
